export const status = {
  All: "",
  Airing: "airing",
  Completed: "completed",
  Aired: "to_be_aired",
  Upcoming: "upcoming",
};

export const order_by = {
  "Default": "",
  Title: "title",
  "Start Date": "start_date",
  "End Date": "end_date",
  Score: "score",
  Type: "type",
  Id: "id",
  Episodes: "episodes",
  Rating: "rating",
};

export const sort = {
  Ascending: "asc",
  Descending: "desc",
};
export const genres = {
  All: "",
  Action: "1",
  Adventure: "2",
  Cars: "3",
  Comedy: "4",
  "Avante Garde": "5",
  Demons: "6",
  Mystery: "7",
  Drama: "8",
  Ecchi: "9",
  Fantasy: "10",
  Game: "11",
  Hentai: "12",
  Historical: "13",
  Horror: "14",
  Kids: "15",
  "Martial Arts": "17",
  Mecha: "18",
  Music: "19",
  Parody: "20",
  Samurai: "21",
  Romance: "22",
  School: "23",
  "Sci Fi": "24",
  Shoujo: "25",
  "Girls Love": "26",
  Shounen: "27",
  "Boys Love": "28",
  Space: "29",
  Sports: "30",
  "Super Power": "31",
  Vampire: "32",
  Harem: "35",
  "Slice Of": "36",
  Supernatural: "37",
  Military: "38",
  Police: "39",
  Psychological: "40",
  Suspense: "41",
  Seinen: "42",
  Josei: "43",
  "Award Winning": "46",
  Gourmet: "47",
  "Work Life": "48",
  Erotica: "49",
};

export const types = {
  All: "",
  TV: "tv",
  OVA: "ova",
  Movie: "movie",
  Special: "special",
  ONA: "ona",
  Music: "music",
};
